### ISSUE TITLE
Files in Datasets contains only "target". Probably the wrong files were uploaded to datasets folder. 

### ISSUE THREAD

**Issue by yanchvlad** [microsoft/methods2test#1]
Files in Datasets contain only "target". Probably the wrong files were uploaded to the datasets folder. Expected Jsons with rich metadata. Thanks.

**Comment by yanchvlad** [comment]
Found them in methods2test-v1.0.

**Comment by micheletufano** [comment]
Hi @yanchvlad,

I cannot replicate your issue.
If I extract a file in datasets (e.g.,`tar -xf methods2test/dataset/eval.tar.bz2`), I get the folders with the JSON files with all the metadata. What do you mean with only "target"? Did you pull the files with `git lfs pull` ?

Note: `methods2test-v1.0` is the first version of this repository, with fewer data points and less info.

**Comment by yanchvlad** [comment]
Hi @micheletufano, yes you are right. Sorry for bothering you.
