### ISSUE TITLE
where to get the grammar file for C++ language?

### ISSUE THREAD

**Issue by lclfans** [microsoft/methods2test#8]
Hi expert, 
   I want to porting the code to support C++ language.
   Where can i get the grammar file for C++ language like the java grammar java-grammar.so?

**Comment by micheletufano** [comment]
Hello,
You can build the grammar file using tree-sitter following similar [steps to this](https://github.com/tree-sitter/py-tree-sitter#usage). The binding for C++ are available [here](https://github.com/tree-sitter/tree-sitter-cpp).
